version: '3.7'

services:
  database_fullstacklvl1:
    image: postgres
    container_name: database_fullstacklvl1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fullstacklvl1
    volumes:
      - pgdata:/data/postgres
    networks:
      - test-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    networks:
      - test-network

volumes:
  pgdata:

networks:
  test-network:
# Use ip of docker inspect cff17c861b74 | grep IPAddress of postgres server
